-- Migration: Create frameworks table and backfill initial data

CREATE TABLE IF NOT EXISTS public.frameworks (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    description TEXT,
    link TEXT,
    picture TEXT,
    initial_upvotes INTEGER DEFAULT 0,
    initial_downvotes INTEGER DEFAULT 0,
    current_upvotes INTEGER DEFAULT 0,
    current_downvotes INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Backfill data
INSERT INTO public.frameworks (name, slug, description, link, picture, initial_upvotes, initial_downvotes, current_upvotes, current_downvotes)
VALUES
('Heart', 'heart', 'The HEART Framework—created in 2010 by Google quantitative UX researchers Kerry Rodden, Hilary Hutchinson, and Xin Fu. It applies the Goals–Signals–Metrics model across five dimensions—Happiness (user sentiment via survey or NPS), Engagement (frequency/intensity of use), Adoption (rate of new feature/product uptake), Retention (how many users return over time), and Task Success (efficiency and error-free completion of key tasks). Teams begin by setting a product goal, identify observable user behaviors (signals) that indicate movement toward that goal, and choose quantifiable metrics for each signal. HEART’s modular structure lets organizations focus on the most relevant UX dimensions—tracking meaningful design impact through concrete data and linking it directly to both user satisfaction and business outcomes', 'https://www.heartframework.com/', '/images/Frameworks/heart.png', 110, 8, 0, 0),
('Attitudinal Surveys', 'attitudinal-surveys', 'Surveys, such as SUS, NPS, CSAT, and CES—are standardized tools designed to capture users’ subjective impressions of a product or service. Originating as early as 1986 with the creation of the System Usability Scale (SUS) by John Brooke, these surveys have become foundational for measuring perceived usability, satisfaction, loyalty, and effort. Net Promoter Score (NPS), introduced by Bain & Company in 2003, gauges user loyalty with a single recommendation-based question, while Customer Satisfaction (CSAT) and Customer Effort Score (CES)—developed in the early 2000s—focus on immediate satisfaction and task ease. These tools are typically deployed after key interactions or tasks, offering product teams quick, comparable feedback on how users feel. By quantifying user sentiment, attitudinal surveys complement behavioral metrics and help teams prioritize improvements, validate design decisions, and monitor UX trends over time.', 'https://userpilot.com/blog/attitudinal-metrics/', '/images/Frameworks/attitudinal.png', 95, 14, 0, 0),
('AARRR', 'aarrr', 'The AARRR Framework, created by Dave McClure in 2007, is a product growth model that tracks user behavior across five key stages: Acquisition, Activation, Retention, Referral, and Revenue. While it’s primarily used for measuring product growth rather than the design of individual features, AARRR provides valuable context for evaluating how design decisions influence user behavior at scale. For example, a streamlined onboarding flow can improve Activation, thoughtful interface patterns can boost Retention, and well-placed sharing mechanisms can drive Referral. By aligning UX metrics with each stage of the funnel, design teams can assess how effectively their work supports overall product performance. AARRR serves as a bridge between UX and growth, making it especially relevant when measuring design impact in data-driven, iterative product environments.', 'https://artkai.io/blog/aarrr-metrics-framework', '/images/Frameworks/aarrr.png', 31, 5, 0, 0),
('Castle', 'castle', 'The CASTLE Framework, introduced in 2025 by UX practitioners building on Nielsen Norman Group research, offers a structured lens tailored for evaluating enterprise and internal tools. CASTLE defines six dimensions—Cognitive Load, Advanced Feature Usage, Satisfaction, Task Efficiency, Learnability, and Errors—that align user behavior with design goals. Teams begin by defining clear performance targets (e.g. reduce errors, speed up task completion), then identify observable signals for each dimension—such as hesitation patterns, feature discoverability, error incidence, or onboarding time—and select measurable metrics accordingly. Especially effective in environments where users must engage with software as part of their job, CASTLE helps product teams track meaningful impact over time, prioritize usability improvements, and justify design decisions with concrete data that matter to productivity and business outcomes', 'https://www.nngroup.com/articles/castle-framework/', '/images/Frameworks/castle.png', 14, 6, 0, 0),
('UX Pyramid', 'ux-pyramid', 'The UX Pyramid, introduced by Aarron Walter—Mailchimp’s UX lead and author of Designing for Emotion—offers a hierarchical framework for crafting digital products that resonate deeply with users. It starts at the base with Functional—making sure the product works—and builds upward to Reliable (consistent performance), Usable (intuitive interfaces), and finally Pleasurable—designs that delight through aesthetic appeal, microinteractions, and emotional resonance. Walter’s pyramid emphasizes that only when foundational needs like functionality, reliability, and usability are met can teams layer on emotional delight to form meaningful user experiences. This progression mirrors human psychological needs and guides designers to engineer products that not only function well but also emotionally engage and retain users.', 'https://www.interaction-design.org/literature/topics/hierarchy-of-needs?srsltid=AfmBOopL9csfdcwbM0VZx03DrHeXHMLXSsoIJ-f7sjvnfZjL6jqBYVDI', '/images/Frameworks/ux-pyramid.png', 7, 2, 0, 0),
('UX Honeycomb', 'ux-honeycomb', 'The UX Honeycomb, developed by Peter Morville in 2004, provides a comprehensive lens for evaluating the quality of user experience across seven dimensions: Useful, Usable, Desirable, Findable, Accessible, Credible, and Valuable. While not a metrics framework in itself, it offers a conceptual structure that helps teams assess whether a design meets essential user and business needs. Each facet of the honeycomb can be mapped to qualitative feedback or paired with quantitative indicators—for example, usability testing for Usable, accessibility audits for Accessible, or sentiment analysis for Desirable. By breaking down UX into distinct but interrelated qualities, the framework guides teams in identifying which aspects of the experience are working well and where improvements are needed, supporting more targeted and balanced measurement of design effectiveness.', 'https://semanticstudios.com/user_experience_design/', '/images/Frameworks/ux-honeycomb.png', 7, 2, 0, 0);
