-- Create metrics table
CREATE TABLE metrics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT UNIQUE,
  description TEXT,
  type TEXT, -- e.g., 'Time', 'Ratio', 'Count', etc.
  metadata JSONB, -- stores associations to views, goals, sources, etc.
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Optional: Index for faster metadata queries
CREATE INDEX metrics_metadata_gin ON metrics USING GIN (metadata);

-- TIME METRICS
INSERT INTO metrics (name, slug, description, type, metadata) VALUES
('Time to Load', 'time-to-load', 'How long it takes for a page or app to fully load', 'Time', '{"data_source":["User Behaviours"],"design_goal":["Usability"],"business_goal":["Adoption"],"user_journey_stage":["Awareness"],"measurement_timing":["Real-time"]}'),
('Time to Onboard', 'time-to-onboard', 'Duration from signup to completing onboarding flow', 'Time', '{"data_source":["User Behaviours"],"design_goal":["Discoverability"],"business_goal":["Adoption"],"user_journey_stage":["Onboarding"],"measurement_timing":["Post-task"]}'),
('Time to First Action', 'time-to-first-action', 'How long until user takes their first interaction', 'Time', '{"data_source":["User Behaviours"],"design_goal":["Engagement"],"business_goal":["Adoption"],"user_journey_stage":["Onboarding"],"measurement_timing":["Real-time"]}'),
('Time to First Success', 'time-to-first-success', 'Duration until user completes first task successfully', 'Time', '{"data_source":["User Behaviours"],"design_goal":["Usability"],"business_goal":["Satisfaction"],"user_journey_stage":["Usage"],"measurement_timing":["Post-task"]}'),
('Time to Value', 'time-to-value', 'How long until user experiences core product benefit', 'Time', '{"data_source":["User Behaviours"],"design_goal":["Engagement"],"business_goal":["Retention"],"user_journey_stage":["Onboarding"],"measurement_timing":["Longitudinal"]}'),
('Time on Task', 'time-on-task', 'Duration spent completing a specific task or goal', 'Time', '{"data_source":["User Behaviours"],"design_goal":["Usability"],"business_goal":["Satisfaction"],"user_journey_stage":["Usage"],"measurement_timing":["Post-task"]}'),
('Time on Page', 'time-on-page', 'How long users spend viewing a particular page', 'Time', '{"data_source":["User Behaviours"],"design_goal":["Engagement"],"business_goal":["Retention"],"user_journey_stage":["Usage"],"measurement_timing":["Real-time"]}'),
('Time per Session', 'time-per-session', 'Average duration of each user session or visit', 'Time', '{"data_source":["User Behaviours"],"design_goal":["Engagement"],"business_goal":["Retention"],"user_journey_stage":["Usage"],"measurement_timing":["Longitudinal"]}');

-- RATIO METRICS
INSERT INTO metrics (name, slug, description, type, metadata) VALUES
('Active User Rate', 'active-user-rate', 'Percentage of registered users who are currently active', 'Ratio', '{"data_source":["User Behaviours"],"business_goal":["Retention"],"measurement_timing":["Longitudinal"]}'),
('Bounce Rate', 'bounce-rate', 'Percentage of users who leave after viewing one page', 'Ratio', '{"data_source":["User Behaviours"],"business_goal":["Adoption"],"user_journey_stage":["Awareness"],"measurement_timing":["Real-time"]}'),
('Click-Through Rate (CTR)', 'click-through-rate', 'Percentage of users who click on a specific link', 'Ratio', '{"data_source":["User Behaviours"],"design_goal":["Engagement"],"business_goal":["Conversion"],"measurement_timing":["Real-time"]}'),
('Confusion Rate', 'confusion-rate', 'Percentage of users who show signs of confusion', 'Ratio', '{"data_source":["User Behaviours"],"design_goal":["Usability"],"business_goal":["Satisfaction"],"measurement_timing":["Post-task"]}'),
('Conversion Rate (CR)', 'conversion-rate', 'Percentage of users who complete desired action', 'Ratio', '{"data_source":["User Behaviours"],"business_goal":["Conversion"],"measurement_timing":["Real-time"]}'),
('Drop-off Rate', 'drop-off-rate', 'Percentage of users who abandon process mid-flow', 'Ratio', '{"data_source":["User Behaviours"],"design_goal":["Usability"],"business_goal":["Conversion"],"measurement_timing":["Real-time"]}'),
('Error Rate', 'error-rate', 'Percentage of user actions that result in errors', 'Ratio', '{"data_source":["User Behaviours"],"design_goal":["Usability"],"business_goal":["Satisfaction"],"measurement_timing":["Real-time"]}'),
('Error Recovery Rate', 'error-recovery-rate', 'Percentage of users who recover from errors', 'Ratio', '{"data_source":["User Behaviours"],"design_goal":["Usability"],"business_goal":["Satisfaction"],"measurement_timing":["Post-task"]}'),
('Exit Rate', 'exit-rate', 'Percentage of users who leave from a specific page', 'Ratio', '{"data_source":["User Behaviours"],"business_goal":["Retention"],"measurement_timing":["Real-time"]}'),
('Feature Adoption Rate', 'feature-adoption-rate', 'Percentage of users who try a new feature', 'Ratio', '{"data_source":["User Behaviours"],"design_goal":["Discoverability"],"business_goal":["Adoption"],"measurement_timing":["Longitudinal"]}'),
('Feature Discovery Rate', 'feature-discovery-rate', 'Percentage of users who find available features', 'Ratio', '{"data_source":["User Behaviours"],"design_goal":["Discoverability"],"business_goal":["Adoption"],"measurement_timing":["Longitudinal"]}'),
('Completion Rate - Onboarding', 'completion-rate-onboarding', 'Percentage who finish the onboarding process', 'Ratio', '{"data_source":["User Behaviours"],"design_goal":["Discoverability"],"business_goal":["Adoption"],"user_journey_stage":["Onboarding"],"measurement_timing":["Post-task"]}'),
('Completion Rate - Form', 'completion-rate-form', 'Percentage who successfully submit forms', 'Ratio', '{"data_source":["User Behaviours"],"design_goal":["Usability"],"business_goal":["Conversion"],"measurement_timing":["Real-time"]}'),
('Completion Rate - Funnel', 'completion-rate-funnel', 'Percentage who complete multi-step processes', 'Ratio', '{"data_source":["User Behaviours"],"design_goal":["Usability"],"business_goal":["Conversion"],"measurement_timing":["Real-time"]}'),
('Retention Rate', 'retention-rate', 'Percentage of users who return over time period', 'Ratio', '{"data_source":["User Behaviours"],"business_goal":["Retention"],"measurement_timing":["Longitudinal"]}'),
('Return Visit Rate', 'return-visit-rate', 'Percentage of users who visit again after first', 'Ratio', '{"data_source":["User Behaviours"],"business_goal":["Retention"],"measurement_timing":["Longitudinal"]}'),
('Success Rate - Task', 'success-rate-task', 'Percentage of users who complete tasks correctly', 'Ratio', '{"data_source":["User Behaviours"],"design_goal":["Usability"],"business_goal":["Satisfaction"],"measurement_timing":["Post-task"]}'),
('Success Rate - Search', 'success-rate-search', 'Percentage of searches that yield useful results', 'Ratio', '{"data_source":["User Behaviours"],"design_goal":["Discoverability"],"business_goal":["Satisfaction"],"measurement_timing":["Real-time"]}'),
('Success Rate - First Click', 'success-rate-first-click', 'Percentage who click correctly on first try', 'Ratio', '{"data_source":["User Behaviours"],"design_goal":["Usability"],"business_goal":["Satisfaction"],"measurement_timing":["Real-time"]}');

-- COUNT METRICS
INSERT INTO metrics (name, slug, description, type, metadata) VALUES
('Users (Total / DAU / WAU / MAU)', 'users', 'Number of unique users in time periods', 'Count', '{"data_source":["User Behaviours"],"business_goal":["Adoption"],"measurement_timing":["Longitudinal"]}'),
('Events', 'events', 'Total number of tracked user interactions', 'Count', '{"data_source":["User Behaviours"],"business_goal":["Engagement"],"measurement_timing":["Real-time"]}'),
('Sessions', 'sessions', 'Number of user visits or app usage periods', 'Count', '{"data_source":["User Behaviours"],"business_goal":["Engagement"],"measurement_timing":["Longitudinal"]}'),
('Clicks', 'clicks', 'Total number of clicks or taps recorded', 'Count', '{"data_source":["User Behaviours"],"business_goal":["Engagement"],"measurement_timing":["Real-time"]}'),
('Page Views', 'page-views', 'Number of pages viewed by users', 'Count', '{"data_source":["User Behaviours"],"business_goal":["Engagement"],"measurement_timing":["Real-time"]}'),
('Errors', 'errors', 'Total count of errors encountered by users', 'Count', '{"data_source":["User Behaviours"],"design_goal":["Usability"],"business_goal":["Satisfaction"],"measurement_timing":["Real-time"]}'),
('Feature Usage', 'feature-usage', 'Number of times features are used', 'Count', '{"data_source":["User Behaviours"],"design_goal":["Engagement"],"business_goal":["Adoption"],"measurement_timing":["Longitudinal"]}'),
('Interaction Depth', 'interaction-depth', 'Average number of actions per user session', 'Count', '{"data_source":["User Behaviours"],"design_goal":["Engagement"],"business_goal":["Retention"],"measurement_timing":["Longitudinal"]}');

-- SCALE METRICS
INSERT INTO metrics (name, slug, description, type, metadata) VALUES
('Aesthetic Appeal', 'aesthetic-appeal', 'User rating of visual design attractiveness', 'Scale', '{"data_source":["User Attitudes"],"design_goal":["Desirability"],"business_goal":["Satisfaction"],"measurement_timing":["Post-task"]}'),
('Brand Perception', 'brand-perception', 'User rating of brand image and reputation', 'Scale', '{"data_source":["User Attitudes"],"design_goal":["Desirability"],"business_goal":["Referral"],"measurement_timing":["Post-task"]}'),
('Confidence', 'confidence', 'User rating of confidence in completing tasks', 'Scale', '{"data_source":["User Attitudes"],"design_goal":["Usability"],"business_goal":["Satisfaction"],"measurement_timing":["Post-task"]}'),
('Customer Effort Score (CES)', 'customer-effort-score', 'User rating of effort required to complete tasks', 'Scale', '{"data_source":["User Attitudes"],"design_goal":["Usability"],"business_goal":["Satisfaction"],"measurement_timing":["Post-task"]}'),
('Customer Satisfaction Score (CSAT)', 'customer-satisfaction-score', 'User rating of overall satisfaction level', 'Scale', '{"data_source":["User Attitudes"],"design_goal":["Satisfaction"],"business_goal":["Satisfaction"],"measurement_timing":["Post-task"]}'),
('First Impression', 'first-impression', 'User rating of initial product experience', 'Scale', '{"data_source":["User Attitudes"],"design_goal":["Desirability"],"business_goal":["Adoption"],"measurement_timing":["Post-task"]}'),
('Net Promoter Score (NPS)', 'net-promoter-score', 'User likelihood to recommend to others rating', 'Scale', '{"data_source":["User Attitudes"],"design_goal":["Engagement"],"business_goal":["Referral"],"measurement_timing":["Longitudinal"]}'),
('Perceived Task Difficulty', 'perceived-task-difficulty', 'User rating of how difficult tasks feel', 'Scale', '{"data_source":["User Attitudes"],"design_goal":["Usability"],"business_goal":["Satisfaction"],"measurement_timing":["Post-task"]}'),
('Trust', 'trust', 'User rating of trust in the product or company', 'Scale', '{"data_source":["User Attitudes"],"design_goal":["Desirability"],"business_goal":["Retention"],"measurement_timing":["Longitudinal"]}'),
('User Satisfaction', 'user-satisfaction', 'User rating of overall experience satisfaction', 'Scale', '{"data_source":["User Attitudes"],"design_goal":["Satisfaction"],"business_goal":["Satisfaction"],"measurement_timing":["Post-task"]}'),
('Visual Design', 'visual-design', 'User rating of interface design quality', 'Scale', '{"data_source":["User Attitudes"],"design_goal":["Desirability"],"business_goal":["Satisfaction"],"measurement_timing":["Post-task"]}');

-- COMPOSITE METRICS
INSERT INTO metrics (name, slug, description, type, metadata) VALUES
('Accessibility Compliance Score', 'accessibility-compliance-score', 'Calculated score of accessibility standards met', 'Composite', '{"data_source":["Non-User Evaluation"],"design_goal":["Usability"],"business_goal":["Satisfaction"],"measurement_timing":["Post-task"]}'),
('Learnability', 'learnability', 'Calculated score of how easy product is to learn', 'Composite', '{"data_source":["User Behaviours"],"design_goal":["Usability"],"business_goal":["Adoption"],"measurement_timing":["Post-task"]}'),
('Heuristic Evaluation Score', 'heuristic-evaluation-score', 'Expert assessment score against usability principles', 'Composite', '{"data_source":["Non-User Evaluation"],"design_goal":["Usability"],"business_goal":["Satisfaction"],"measurement_timing":["Post-task"]}'),
('Navigation Efficiency Score', 'navigation-efficiency-score', 'Calculated score of navigation effectiveness', 'Composite', '{"data_source":["User Behaviours"],"design_goal":["Usability"],"business_goal":["Satisfaction"],"measurement_timing":["Post-task"]}'),
('Path Efficiency Score', 'path-efficiency-score', 'Calculated score of optimal path completion', 'Composite', '{"data_source":["User Behaviours"],"design_goal":["Usability"],"business_goal":["Conversion"],"measurement_timing":["Post-task"]}'),
('Single Usability Metric (SUM)', 'single-usability-metric', 'Combined score of multiple usability measures', 'Composite', '{"data_source":["User Behaviours"],"design_goal":["Usability"],"business_goal":["Satisfaction"],"measurement_timing":["Post-task"]}'),
('System Usability Scale (SUS)', 'system-usability-scale', 'Standardized 10-item usability questionnaire score', 'Composite', '{"data_source":["User Attitudes"],"design_goal":["Usability"],"business_goal":["Satisfaction"],"measurement_timing":["Post-task"]}'),
('Usability Metric for User Experience (UMUX)', 'usability-metric-for-user-experience', 'Condensed usability assessment score', 'Composite', '{"data_source":["User Attitudes"],"design_goal":["Usability"],"business_goal":["Satisfaction"],"measurement_timing":["Post-task"]}'),
('User Engagement Score', 'user-engagement-score', 'Calculated score combining engagement behaviors', 'Composite', '{"data_source":["User Behaviours"],"design_goal":["Engagement"],"business_goal":["Retention"],"measurement_timing":["Longitudinal"]}'),
('Workflow Efficiency Score', 'workflow-efficiency-score', 'Calculated score of process completion efficiency', 'Composite', '{"data_source":["User Behaviours"],"design_goal":["Usability"],"business_goal":["Conversion"],"measurement_timing":["Post-task"]}');

-- MONEY METRICS
INSERT INTO metrics (name, slug, description, type, metadata) VALUES
('Transactions Number', 'transactions-number', 'Total count of completed financial transactions', 'Money', '{"data_source":["User Behaviours"],"business_goal":["Revenue"],"measurement_timing":["Longitudinal"]}'),
('Transaction Value', 'transaction-value', 'Total monetary value of transactions', 'Money', '{"data_source":["User Behaviours"],"business_goal":["Revenue"],"measurement_timing":["Longitudinal"]}'),
('Average Order Value', 'average-order-value', 'Mean monetary value per transaction or order', 'Money', '{"data_source":["User Behaviours"],"business_goal":["Revenue"],"measurement_timing":["Longitudinal"]}'),
('Customer Acquisition Cost (CAC)', 'customer-acquisition-cost', 'Cost to acquire each new customer', 'Money', '{"data_source":["Non-User Evaluation"],"business_goal":["Adoption"],"measurement_timing":["Longitudinal"]}'),
('Customer Lifetime Value (CLV)', 'customer-lifetime-value', 'Total revenue expected from customer relationship', 'Money', '{"data_source":["User Behaviours"],"business_goal":["Retention"],"measurement_timing":["Longitudinal"]}'),
('Revenue per User', 'revenue-per-user', 'Average revenue generated per user or customer', 'Money', '{"data_source":["User Behaviours"],"business_goal":["Revenue"],"measurement_timing":["Longitudinal"]}');

-- Make slug column required after backfill
ALTER TABLE metrics ALTER COLUMN slug SET NOT NULL;
