-- ============================================================================
-- MIGRATION: Fix Methods Table ID Column to Allow Manual Assignment
-- Date: August 28, 2025
-- Purpose: Remove auto-generation restriction from methods.id column to allow
--          manual ID assignment for special cases like "All in" view
-- ============================================================================

BEGIN;

-- ============================================================================
-- STEP 1: Check current table structure and constraints
-- ============================================================================

-- Check the current column definition
SELECT column_name, data_type, is_nullable, column_default, is_identity, identity_generation
FROM information_schema.columns 
WHERE table_name = 'methods' AND column_name = 'id';

-- ============================================================================
-- STEP 2: Modify the ID column to remove GENERATED ALWAYS restriction
-- ============================================================================

-- Change the identity column from GENERATED ALWAYS to GENERATED BY DEFAULT
-- This allows manual insertion while still auto-generating when not specified
ALTER TABLE methods ALTER COLUMN id SET GENERATED BY DEFAULT;

-- ============================================================================
-- STEP 3: Verify the change was successful
-- ============================================================================

-- Check the updated column definition
SELECT column_name, data_type, is_nullable, column_default, is_identity, identity_generation
FROM information_schema.columns 
WHERE table_name = 'methods' AND column_name = 'id';

-- ============================================================================
-- STEP 4: Test manual ID insertion (this should now work)
-- ============================================================================

-- Test inserting a method with manual ID (we'll delete it after testing)
INSERT INTO methods (id, collection_id, name, slug, description, current_upvotes, current_downvotes, initial_score, metadata)
VALUES (999, 1, 'Test Manual ID', 'test-manual', 'Test for manual ID assignment', 0, 0, 0, '{"test":true}');

-- Verify it was inserted
SELECT id, name, slug FROM methods WHERE id = 999;

-- Clean up test record
DELETE FROM methods WHERE id = 999;

COMMIT;

-- ============================================================================
-- NOTES:
-- ============================================================================
-- After running this migration, you can:
-- 1. Insert methods with manual IDs when needed
-- 2. Still get auto-generated IDs when you don't specify an ID
-- 3. Use ID = 0 for the "All in" view as originally planned
-- 4. This change is backwards compatible with existing code
-- ============================================================================
